### ISSUE TITLE
About the log file

### ISSUE THREAD

**Issue by Mrkkew** [bitreidgroup/DSCNet#1]
I have run the provided source code but didn't reach the performance in the paper. Could you please provide the log file? Did you test the model after the whole training process or just use the 1 trail performance as the final performance? The 1 trail performance is not accurate and not fair compared to previous methods.

**Comment by bitreidgroup** [comment]
Hi, thank you for your interest in our DSCNet! As we introduced in our paper, we employed channel augmentation in our experiments. Due to random channel exchange and erasing, it DOES affect the performance. However, Rank-1 73.89% in the all-search mode on the SYSU-MM01 dataset is the result during the whole training process. In addition, we also evaluate different trials. The best performance of DSCNet we have got on a single trial is better than 77.95 % (SYSU-MM01 all-search). If you can not reproduce the results, please simply try more times. If you have other questions, please let me know.

**Comment by bitreidgroup** [comment]
Regarding the training log, please stay tuned.

**Comment by Mrkkew** [comment]
==> Preparing Data Loader...
197
[ 9080  9069  9055 ... 20043 20045 20033]
[3927 3921 3889 ... 9662 9650 9659]
Epoch: [197][0/927] Time: 0.689 (0.689) lr:0.001 Loss: 0.1286 (0.1286) iLoss: 0.0292 (0.0292) TLoss: 0.0118 (0.0118) KLoss: 0.8764 (0.8764) BASELoss: 0.7270 (0.7270) MLoss: 0.6726 (0.6726) KILoss: 0.0544 (0.0544) Accu: 99.31
Epoch: [197][50/927] Time: 0.289 (0.301) lr:0.001 Loss: 0.1710 (0.1505) iLoss: 0.0421 (0.0447) TLoss: 0.0408 (0.0165) KLoss: 0.8804 (0.8935) BASELoss: 0.7206 (0.7329) MLoss: 0.6666 (0.6807) KILoss: 0.0539 (0.0522) Accu: 98.92
Epoch: [197][100/927] Time: 0.293 (0.297) lr:0.001 Loss: 0.1222 (0.1472) iLoss: 0.0292 (0.0431) TLoss: 0.0048 (0.0141) KLoss: 0.8825 (0.8999) BASELoss: 0.7288 (0.7337) MLoss: 0.6765 (0.6814) KILoss: 0.0524 (0.0523) Accu: 99.09
Epoch: [197][150/927] Time: 0.296 (0.296) lr:0.001 Loss: 0.1462 (0.1501) iLoss: 0.0539 (0.0449) TLoss: 0.0046 (0.0150) KLoss: 0.8767 (0.9018) BASELoss: 0.7605 (0.7341) MLoss: 0.7073 (0.6818) KILoss: 0.0532 (0.0523) Accu: 99.08
Epoch: [197][200/927] Time: 0.285 (0.296) lr:0.001 Loss: 0.1556 (0.1497) iLoss: 0.0556 (0.0442) TLoss: 0.0180 (0.0153) KLoss: 0.8206 (0.9016) BASELoss: 0.7474 (0.7332) MLoss: 0.6945 (0.6811) KILoss: 0.0529 (0.0522) Accu: 99.10
Epoch: [197][250/927] Time: 0.298 (0.296) lr:0.001 Loss: 0.1298 (0.1507) iLoss: 0.0440 (0.0447) TLoss: 0.0020 (0.0154) KLoss: 0.8374 (0.9061) BASELoss: 0.7188 (0.7330) MLoss: 0.6670 (0.6808) KILoss: 0.0518 (0.0522) Accu: 99.04
Epoch: [197][300/927] Time: 0.294 (0.296) lr:0.001 Loss: 0.1328 (0.1512) iLoss: 0.0359 (0.0448) TLoss: 0.0065 (0.0156) KLoss: 0.9034 (0.9076) BASELoss: 0.7257 (0.7333) MLoss: 0.6736 (0.6812) KILoss: 0.0521 (0.0521) Accu: 99.01
Epoch: [197][350/927] Time: 0.301 (0.296) lr:0.001 Loss: 0.1161 (0.1511) iLoss: 0.0297 (0.0446) TLoss: 0.0000 (0.0155) KLoss: 0.8642 (0.9096) BASELoss: 0.7269 (0.7336) MLoss: 0.6739 (0.6814) KILoss: 0.0530 (0.0522) Accu: 99.02
Epoch: [197][400/927] Time: 0.297 (0.296) lr:0.001 Loss: 0.1822 (0.1500) iLoss: 0.0709 (0.0441) TLoss: 0.0097 (0.0152) KLoss: 1.0170 (0.9072) BASELoss: 0.7272 (0.7337) MLoss: 0.6757 (0.6815) KILoss: 0.0515 (0.0521) Accu: 99.04
Epoch: [197][450/927] Time: 0.298 (0.296) lr:0.001 Loss: 0.2258 (0.1501) iLoss: 0.1196 (0.0445) TLoss: 0.0036 (0.0149) KLoss: 1.0257 (0.9064) BASELoss: 0.7310 (0.7342) MLoss: 0.6769 (0.6820) KILoss: 0.0541 (0.0522) Accu: 99.06
Epoch: [197][500/927] Time: 0.302 (0.296) lr:0.001 Loss: 0.1161 (0.1507) iLoss: 0.0236 (0.0448) TLoss: 0.0000 (0.0154) KLoss: 0.9249 (0.9054) BASELoss: 0.7420 (0.7345) MLoss: 0.6900 (0.6823) KILoss: 0.0520 (0.0522) Accu: 99.02
Epoch: [197][550/927] Time: 0.300 (0.296) lr:0.001 Loss: 0.1145 (0.1506) iLoss: 0.0269 (0.0447) TLoss: 0.0000 (0.0154) KLoss: 0.8761 (0.9052) BASELoss: 0.7388 (0.7345) MLoss: 0.6860 (0.6823) KILoss: 0.0528 (0.0522) Accu: 99.01
Epoch: [197][600/927] Time: 0.301 (0.297) lr:0.001 Loss: 0.1172 (0.1505) iLoss: 0.0284 (0.0448) TLoss: 0.0011 (0.0152) KLoss: 0.8773 (0.9051) BASELoss: 0.7397 (0.7347) MLoss: 0.6892 (0.6825) KILoss: 0.0505 (0.0522) Accu: 99.02
Epoch: [197][650/927] Time: 0.298 (0.297) lr:0.001 Loss: 0.1385 (0.1502) iLoss: 0.0330 (0.0448) TLoss: 0.0045 (0.0148) KLoss: 1.0097 (0.9054) BASELoss: 0.7379 (0.7344) MLoss: 0.6841 (0.6823) KILoss: 0.0538 (0.0522) Accu: 99.05
Epoch: [197][700/927] Time: 0.306 (0.297) lr:0.001 Loss: 0.1266 (0.1508) iLoss: 0.0374 (0.0452) TLoss: 0.0000 (0.0150) KLoss: 0.8917 (0.9061) BASELoss: 0.7277 (0.7348) MLoss: 0.6754 (0.6826) KILoss: 0.0523 (0.0522) Accu: 99.04
Epoch: [197][750/927] Time: 0.296 (0.297) lr:0.001 Loss: 0.1971 (0.1513) iLoss: 0.0820 (0.0456) TLoss: 0.0221 (0.0152) KLoss: 0.9292 (0.9051) BASELoss: 0.7626 (0.7344) MLoss: 0.7103 (0.6822) KILoss: 0.0523 (0.0522) Accu: 99.01
Epoch: [197][800/927] Time: 0.295 (0.297) lr:0.001 Loss: 0.1706 (0.1512) iLoss: 0.0567 (0.0455) TLoss: 0.0262 (0.0153) KLoss: 0.8776 (0.9044) BASELoss: 0.7320 (0.7343) MLoss: 0.6800 (0.6821) KILoss: 0.0520 (0.0522) Accu: 99.00
Epoch: [197][850/927] Time: 0.286 (0.297) lr:0.001 Loss: 0.1646 (0.1511) iLoss: 0.0556 (0.0454) TLoss: 0.0143 (0.0153) KLoss: 0.9462 (0.9045) BASELoss: 0.7550 (0.7342) MLoss: 0.7014 (0.6821) KILoss: 0.0536 (0.0522) Accu: 99.00
Epoch: [197][900/927] Time: 0.306 (0.297) lr:0.001 Loss: 0.1573 (0.1511) iLoss: 0.0551 (0.0452) TLoss: 0.0055 (0.0154) KLoss: 0.9668 (0.9050) BASELoss: 0.7042 (0.7341) MLoss: 0.6526 (0.6819) KILoss: 0.0515 (0.0522) Accu: 99.00
Test Epoch: 197
Extracting Gallery Feature...
Extracting Time:	 0.871
Extracting Query Feature...
Extracting Time:	 4.801
Evaluation Time:	 5.294
POOL:   Rank-1: 68.55% | Rank-5: 90.14% | Rank-10: 95.64%| Rank-20: 98.63%| mAP: 65.60%| mINP: 52.67%
FC:   Rank-1: 70.42% | Rank-5: 92.06% | Rank-10: 96.56%| Rank-20: 99.00%| mAP: 66.85%| mINP: 52.67%
Best Epoch [106]   Best Rank-1 71.73%
==> Preparing Data Loader...
198
[ 489  501  552 ... 1652 1689 1665]
[211 235 208 ... 657 659 679]
Epoch: [198][0/927] Time: 0.740 (0.740) lr:0.001 Loss: 0.1220 (0.1220) iLoss: 0.0342 (0.0342) TLoss: 0.0006 (0.0006) KLoss: 0.8721 (0.8721) BASELoss: 0.7433 (0.7433) MLoss: 0.6899 (0.6899) KILoss: 0.0534 (0.0534) Accu: 100.00
Epoch: [198][50/927] Time: 0.299 (0.302) lr:0.001 Loss: 0.1132 (0.1488) iLoss: 0.0234 (0.0465) TLoss: 0.0041 (0.0125) KLoss: 0.8567 (0.8983) BASELoss: 0.7234 (0.7300) MLoss: 0.6718 (0.6779) KILoss: 0.0515 (0.0521) Accu: 99.06
Epoch: [198][100/927] Time: 0.288 (0.298) lr:0.001 Loss: 0.1247 (0.1460) iLoss: 0.0336 (0.0439) TLoss: 0.0045 (0.0125) KLoss: 0.8657 (0.8953) BASELoss: 0.7259 (0.7300) MLoss: 0.6748 (0.6779) KILoss: 0.0511 (0.0521) Accu: 99.14
Epoch: [198][150/927] Time: 0.295 (0.298) lr:0.001 Loss: 0.1833 (0.1495) iLoss: 0.0444 (0.0449) TLoss: 0.0387 (0.0146) KLoss: 1.0022 (0.8992) BASELoss: 0.7293 (0.7311) MLoss: 0.6792 (0.6790) KILoss: 0.0501 (0.0521) Accu: 98.98
Epoch: [198][200/927] Time: 0.297 (0.297) lr:0.001 Loss: 0.1851 (0.1494) iLoss: 0.0509 (0.0448) TLoss: 0.0350 (0.0145) KLoss: 0.9914 (0.9007) BASELoss: 0.7374 (0.7306) MLoss: 0.6835 (0.6784) KILoss: 0.0540 (0.0522) Accu: 99.03
Epoch: [198][250/927] Time: 0.297 (0.297) lr:0.001 Loss: 0.1839 (0.1497) iLoss: 0.0938 (0.0451) TLoss: 0.0032 (0.0144) KLoss: 0.8686 (0.9014) BASELoss: 0.7043 (0.7296) MLoss: 0.6532 (0.6775) KILoss: 0.0511 (0.0521) Accu: 99.04
Epoch: [198][300/927] Time: 0.287 (0.297) lr:0.001 Loss: 0.1361 (0.1519) iLoss: 0.0387 (0.0460) TLoss: 0.0000 (0.0156) KLoss: 0.9747 (0.9026) BASELoss: 0.7398 (0.7302) MLoss: 0.6846 (0.6781) KILoss: 0.0552 (0.0521) Accu: 98.96
Epoch: [198][350/927] Time: 0.296 (0.297) lr:0.001 Loss: 0.1129 (0.1520) iLoss: 0.0337 (0.0462) TLoss: 0.0000 (0.0154) KLoss: 0.7924 (0.9044) BASELoss: 0.7217 (0.7305) MLoss: 0.6723 (0.6784) KILoss: 0.0494 (0.0521) Accu: 98.98
Epoch: [198][400/927] Time: 0.298 (0.297) lr:0.001 Loss: 0.1125 (0.1509) iLoss: 0.0270 (0.0455) TLoss: 0.0001 (0.0149) KLoss: 0.8532 (0.9047) BASELoss: 0.7620 (0.7300) MLoss: 0.7091 (0.6778) KILoss: 0.0529 (0.0522) Accu: 99.01
Epoch: [198][450/927] Time: 0.298 (0.297) lr:0.001 Loss: 0.1086 (0.1502) iLoss: 0.0274 (0.0455) TLoss: 0.0153 (0.0144) KLoss: 0.6586 (0.9037) BASELoss: 0.7115 (0.7299) MLoss: 0.6599 (0.6778) KILoss: 0.0516 (0.0522) Accu: 99.06
Epoch: [198][500/927] Time: 0.308 (0.297) lr:0.001 Loss: 0.1481 (0.1500) iLoss: 0.0531 (0.0454) TLoss: 0.0001 (0.0143) KLoss: 0.9490 (0.9027) BASELoss: 0.7387 (0.7299) MLoss: 0.6841 (0.6777) KILoss: 0.0545 (0.0522) Accu: 99.07
Epoch: [198][550/927] Time: 0.308 (0.298) lr:0.001 Loss: 0.1510 (0.1497) iLoss: 0.0558 (0.0453) TLoss: 0.0167 (0.0140) KLoss: 0.7850 (0.9029) BASELoss: 0.7143 (0.7299) MLoss: 0.6628 (0.6777) KILoss: 0.0515 (0.0522) Accu: 99.08
Epoch: [198][600/927] Time: 0.294 (0.298) lr:0.001 Loss: 0.2274 (0.1498) iLoss: 0.0885 (0.0453) TLoss: 0.0498 (0.0142) KLoss: 0.8910 (0.9029) BASELoss: 0.7207 (0.7300) MLoss: 0.6681 (0.6778) KILoss: 0.0525 (0.0522) Accu: 99.05
Epoch: [198][650/927] Time: 0.297 (0.298) lr:0.001 Loss: 0.1118 (0.1499) iLoss: 0.0401 (0.0452) TLoss: 0.0000 (0.0144) KLoss: 0.7174 (0.9025) BASELoss: 0.7323 (0.7302) MLoss: 0.6780 (0.6779) KILoss: 0.0543 (0.0522) Accu: 99.03
Epoch: [198][700/927] Time: 0.292 (0.298) lr:0.001 Loss: 0.1921 (0.1506) iLoss: 0.0590 (0.0455) TLoss: 0.0329 (0.0148) KLoss: 1.0025 (0.9036) BASELoss: 0.7731 (0.7301) MLoss: 0.7205 (0.6778) KILoss: 0.0526 (0.0522) Accu: 99.02
Epoch: [198][750/927] Time: 0.296 (0.298) lr:0.001 Loss: 0.1322 (0.1506) iLoss: 0.0393 (0.0455) TLoss: 0.0000 (0.0147) KLoss: 0.9294 (0.9039) BASELoss: 0.7439 (0.7304) MLoss: 0.6893 (0.6781) KILoss: 0.0546 (0.0522) Accu: 99.02
Epoch: [198][800/927] Time: 0.295 (0.297) lr:0.001 Loss: 0.1926 (0.1505) iLoss: 0.0937 (0.0455) TLoss: 0.0117 (0.0145) KLoss: 0.8723 (0.9050) BASELoss: 0.7236 (0.7305) MLoss: 0.6715 (0.6782) KILoss: 0.0522 (0.0522) Accu: 99.04
Epoch: [198][850/927] Time: 0.305 (0.297) lr:0.001 Loss: 0.1600 (0.1510) iLoss: 0.0479 (0.0456) TLoss: 0.0157 (0.0149) KLoss: 0.9647 (0.9043) BASELoss: 0.7297 (0.7306) MLoss: 0.6766 (0.6783) KILoss: 0.0531 (0.0522) Accu: 99.01
Epoch: [198][900/927] Time: 0.297 (0.297) lr:0.001 Loss: 0.1510 (0.1510) iLoss: 0.0388 (0.0456) TLoss: 0.0121 (0.0149) KLoss: 1.0011 (0.9039) BASELoss: 0.7407 (0.7307) MLoss: 0.6876 (0.6785) KILoss: 0.0531 (0.0522) Accu: 99.01
Test Epoch: 198
Extracting Gallery Feature...
Extracting Time:	 0.832
Extracting Query Feature...
Extracting Time:	 4.851
Evaluation Time:	 5.380
POOL:   Rank-1: 67.95% | Rank-5: 90.01% | Rank-10: 95.48%| Rank-20: 98.63%| mAP: 65.30%| mINP: 52.26%
FC:   Rank-1: 70.52% | Rank-5: 91.98% | Rank-10: 96.11%| Rank-20: 98.82%| mAP: 66.71%| mINP: 52.45%
Best Epoch [106]   Best Rank-1 71.73%
==> Preparing Data Loader...
199
[11787 11719 11744 ... 11633 11611 11604]
[5060 5063 5064 ... 5033 5029 5027]
Epoch: [199][0/927] Time: 0.685 (0.685) lr:0.001 Loss: 0.1433 (0.1433) iLoss: 0.0525 (0.0525) TLoss: 0.0000 (0.0000) KLoss: 0.9081 (0.9081) BASELoss: 0.7618 (0.7618) MLoss: 0.7082 (0.7082) KILoss: 0.0537 (0.0537) Accu: 100.00
Epoch: [199][50/927] Time: 0.293 (0.302) lr:0.001 Loss: 0.2243 (0.1617) iLoss: 0.0610 (0.0492) TLoss: 0.0615 (0.0206) KLoss: 1.0173 (0.9190) BASELoss: 0.7382 (0.7332) MLoss: 0.6848 (0.6807) KILoss: 0.0534 (0.0525) Accu: 98.54
Epoch: [199][100/927] Time: 0.300 (0.300) lr:0.001 Loss: 0.1060 (0.1537) iLoss: 0.0281 (0.0457) TLoss: 0.0000 (0.0172) KLoss: 0.7786 (0.9080) BASELoss: 0.7577 (0.7334) MLoss: 0.7045 (0.6810) KILoss: 0.0532 (0.0524) Accu: 98.79
Epoch: [199][150/927] Time: 0.296 (0.300) lr:0.001 Loss: 0.1234 (0.1526) iLoss: 0.0390 (0.0462) TLoss: 0.0000 (0.0158) KLoss: 0.8440 (0.9055) BASELoss: 0.7385 (0.7321) MLoss: 0.6855 (0.6797) KILoss: 0.0529 (0.0524) Accu: 98.93
Epoch: [199][200/927] Time: 0.301 (0.300) lr:0.001 Loss: 0.3100 (0.1504) iLoss: 0.0691 (0.0448) TLoss: 0.1490 (0.0152) KLoss: 0.9184 (0.9049) BASELoss: 0.7246 (0.7322) MLoss: 0.6702 (0.6798) KILoss: 0.0545 (0.0524) Accu: 98.98
Epoch: [199][250/927] Time: 0.297 (0.300) lr:0.001 Loss: 0.1278 (0.1501) iLoss: 0.0406 (0.0449) TLoss: 0.0000 (0.0146) KLoss: 0.8721 (0.9068) BASELoss: 0.7282 (0.7325) MLoss: 0.6760 (0.6801) KILoss: 0.0523 (0.0523) Accu: 99.03
Epoch: [199][300/927] Time: 0.293 (0.299) lr:0.001 Loss: 0.0988 (0.1505) iLoss: 0.0239 (0.0450) TLoss: 0.0000 (0.0144) KLoss: 0.7481 (0.9099) BASELoss: 0.7376 (0.7325) MLoss: 0.6840 (0.6802) KILoss: 0.0536 (0.0523) Accu: 99.05
Epoch: [199][350/927] Time: 0.299 (0.299) lr:0.001 Loss: 0.1506 (0.1502) iLoss: 0.0450 (0.0452) TLoss: 0.0124 (0.0140) KLoss: 0.9328 (0.9108) BASELoss: 0.7186 (0.7332) MLoss: 0.6685 (0.6809) KILoss: 0.0501 (0.0523) Accu: 99.08
Epoch: [199][400/927] Time: 0.304 (0.299) lr:0.001 Loss: 0.1222 (0.1505) iLoss: 0.0300 (0.0452) TLoss: 0.0000 (0.0144) KLoss: 0.9217 (0.9085) BASELoss: 0.7386 (0.7333) MLoss: 0.6864 (0.6809) KILoss: 0.0522 (0.0523) Accu: 99.04
Epoch: [199][450/927] Time: 0.298 (0.299) lr:0.001 Loss: 0.1439 (0.1490) iLoss: 0.0284 (0.0444) TLoss: 0.0257 (0.0140) KLoss: 0.8986 (0.9062) BASELoss: 0.7639 (0.7335) MLoss: 0.7123 (0.6812) KILoss: 0.0516 (0.0523) Accu: 99.07
Epoch: [199][500/927] Time: 0.295 (0.299) lr:0.001 Loss: 0.1730 (0.1496) iLoss: 0.0640 (0.0448) TLoss: 0.0214 (0.0142) KLoss: 0.8767 (0.9056) BASELoss: 0.7155 (0.7332) MLoss: 0.6648 (0.6810) KILoss: 0.0506 (0.0523) Accu: 99.06
Epoch: [199][550/927] Time: 0.301 (0.299) lr:0.001 Loss: 0.1206 (0.1494) iLoss: 0.0356 (0.0449) TLoss: 0.0000 (0.0140) KLoss: 0.8493 (0.9050) BASELoss: 0.7473 (0.7333) MLoss: 0.6962 (0.6811) KILoss: 0.0511 (0.0522) Accu: 99.07
Epoch: [199][600/927] Time: 0.297 (0.299) lr:0.001 Loss: 0.1309 (0.1491) iLoss: 0.0458 (0.0446) TLoss: 0.0049 (0.0141) KLoss: 0.8019 (0.9045) BASELoss: 0.7156 (0.7331) MLoss: 0.6637 (0.6808) KILoss: 0.0519 (0.0522) Accu: 99.07
Epoch: [199][650/927] Time: 0.287 (0.299) lr:0.001 Loss: 0.1554 (0.1497) iLoss: 0.0533 (0.0450) TLoss: 0.0132 (0.0142) KLoss: 0.8891 (0.9040) BASELoss: 0.7535 (0.7334) MLoss: 0.7021 (0.6811) KILoss: 0.0514 (0.0522) Accu: 99.06
Epoch: [199][700/927] Time: 0.300 (0.298) lr:0.001 Loss: 0.1099 (0.1488) iLoss: 0.0284 (0.0445) TLoss: 0.0000 (0.0140) KLoss: 0.8153 (0.9026) BASELoss: 0.7313 (0.7332) MLoss: 0.6784 (0.6810) KILoss: 0.0528 (0.0522) Accu: 99.08
Epoch: [199][750/927] Time: 0.309 (0.298) lr:0.001 Loss: 0.1296 (0.1492) iLoss: 0.0309 (0.0446) TLoss: 0.0099 (0.0145) KLoss: 0.8876 (0.9023) BASELoss: 0.7549 (0.7336) MLoss: 0.7017 (0.6813) KILoss: 0.0531 (0.0523) Accu: 99.05
Epoch: [199][800/927] Time: 0.292 (0.298) lr:0.001 Loss: 0.1270 (0.1496) iLoss: 0.0421 (0.0447) TLoss: 0.0073 (0.0146) KLoss: 0.7769 (0.9028) BASELoss: 0.7580 (0.7338) MLoss: 0.7056 (0.6815) KILoss: 0.0524 (0.0522) Accu: 99.04
Epoch: [199][850/927] Time: 0.295 (0.299) lr:0.001 Loss: 0.1566 (0.1497) iLoss: 0.0591 (0.0448) TLoss: 0.0000 (0.0146) KLoss: 0.9745 (0.9037) BASELoss: 0.7460 (0.7338) MLoss: 0.6952 (0.6815) KILoss: 0.0507 (0.0522) Accu: 99.04
Epoch: [199][900/927] Time: 0.295 (0.298) lr:0.001 Loss: 0.1279 (0.1498) iLoss: 0.0380 (0.0450) TLoss: 0.0000 (0.0144) KLoss: 0.8993 (0.9035) BASELoss: 0.7174 (0.7339) MLoss: 0.6676 (0.6816) KILoss: 0.0498 (0.0522) Accu: 99.04
Test Epoch: 199
Extracting Gallery Feature...
Extracting Time:	 0.841
Extracting Query Feature...
Extracting Time:	 4.837
Evaluation Time:	 5.593
POOL:   Rank-1: 67.53% | Rank-5: 89.88% | Rank-10: 95.74%| Rank-20: 98.55%| mAP: 64.94%| mINP: 51.84%
FC:   Rank-1: 69.97% | Rank-5: 92.11% | Rank-10: 96.29%| Rank-20: 98.82%| mAP: 66.48%| mINP: 52.27%
Best Epoch [106]   Best Rank-1 71.73%
This is my reproduction results on SYSU under the all search mode. As we can see, the Rank-1 accuracy cannot reach Rank-1 73.89%.

**Comment by bitreidgroup** [comment]
Please simply try ** more ** times. It is affected by random factors.

**Comment by Mrkkew** [comment]
I have tried many times but cannot achieve similar results in the paper. Although it may be affected by random factors, the performance of the models should not vary so much. Could you please provide the trained weights of your final model?

**Comment by bitreidgroup** [comment]
Hi, thank you for your great interest in our DSCNet. I believe that you have run the experiments many times. I have uploaded the checkpoints to google drive you can easily run the scripts to download the [checkpoints](https://drive.google.com/file/d/1nm_plUl4HjikpL1vwfHGkVBnIA02kMls/view?usp=sharing). And I sincerely hope that the weights can help your research. 
```
gdown 1nm_plUl4HjikpL1vwfHGkVBnIA02kMls
```
if you did not install gdown before, you can simply install gdown with pip:
```
pip install gdown
```

**Comment by bitreidgroup** [comment]
> I have tried many times but cannot achieve similar results in the paper. Although it may be affected by random factors, the performance of the models should not vary so much. Could you please provide the trained weights of your final model?

Hi, thank you for your great interest in our DSCNet. I believe that you have run the experiments many times. I have uploaded the checkpoints to google drive you can easily run the scripts to download the [checkpoints](https://drive.google.com/file/d/1nm_plUl4HjikpL1vwfHGkVBnIA02kMls/view?usp=sharing). And I sincerely hope that the weights can help your research. I've updated README documentation with the checkpoints link.
```
gdown 1nm_plUl4HjikpL1vwfHGkVBnIA02kMls
```
if you did not install gdown before, you can simply install gdown with pip:
```
pip install gdown
```

**Comment by bitreidgroup** [comment]
If you have any other issues, please feel free comment below.
